### ISSUE TITLE
Recommendation for usage with Ecto?

### ISSUE THREAD

**Issue by phyllisstein** [sheharyarn/better_params#5]
Hey there! I really love the idea of this module, preferring the feel of atom keys by a mile, but it's creating some trouble with Ecto. In cases where I just want to dump a whole mess of params into a `cast` call, Ecto throws an error on encountering mixed keys:

```
    ** (Ecto.CastError) expected params to be a map with atoms or string keys, got a map with mixed keys: %{:author_email => "daniel@daniel.sh", :author_name => "Daniel P. Shannon", :body => "Foo bar baz quux.", :title => "Foo Bar Baz Quux", "author_email" => "daniel@daniel.sh", "author_name" => "Daniel P. Shannon", "body" => "Foo bar baz quux.", "title" => "Foo Bar Baz Quux"}
        (ecto) lib/ecto/changeset.ex:542: anonymous fn/3 in Ecto.Changeset.convert_params/1
        (ecto) lib/ecto/changeset.ex:537: Ecto.Changeset.convert_params/1
        (ecto) lib/ecto/changeset.ex:442: Ecto.Changeset.do_cast/7
        (poppins_schema) lib/poppins_schema/crm/query.ex:16: PoppinsSchema.CRM.Query.submit_changeset/2
        (poppins_schema) lib/poppins_schema/crm/crm.ex:7: PoppinsSchema.CRM.submit_query/1
        (poppins_web) lib/poppins_web/controllers/crm/query_controller.ex:9: PoppinsWeb.CRM.QueryController.create/2
        (poppins_web) lib/poppins_web/controllers/crm/query_controller.ex:1: PoppinsWeb.CRM.QueryController.action/2
```

Frankly this strikes me as a little silly of Ecto, but I was curious whether there was a way to either drop the duplicate fallback strings or get around the cast issue without explicitly rebuilding the params map for every endpoint.

(Sorry for a bit of a StackOverflow-y question, but I guess it's part feature request since I'd love to just omit the strings. 😬 )

**Comment by sheharyarn** [comment]
I've been using this with ecto for quite some time now, and haven't had this issue so far. I'm assuming that by "whole mess of params", you mean the root `params` map itself - so I can see why this error would occur.

Ideally, you should not send parameters directly & dump the whole `params` map. Instead, they should be under one (or more) objects/keys.

---

This is still an interesting feature request though, and I can see other use-cases for it. But unfortunately, because of some other time constraints, I can't get to it for the next 2 weeks or so.

But feel free to send in a Pull Request and I'll see what I can do (also gain some points since it's [Hacktoberfest!](https://hacktoberfest.digitalocean.com/) 😛)
